apiVersion: v1
kind: Secret
metadata:
  name: clinica-connect-secret
  namespace: clinica-connect
type: Opaque
stringData:
  POSTGRES_USER: clinic_user
  POSTGRES_PASSWORD: clinic_pass
  POSTGRES_DB: clinic_connect
